[package]
edition = "2021"
name = "aos_data_proxy"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
aruna-rust-api = "1.0.0-rc.15.1"
aruna-file = "0.1.14"
async-channel = "1.8.0"
async-stream = "0.3.4"
async-trait = "0.1.64"
aws-config = "0.54.1"
aws-sdk-s3 = "0.24.0"
aws-smithy-http = "0.54.3"
base64 = "0.21.0"
bytes = "1.4.0"
chrono = "0.4.23"
dotenv = "0.15.0"
env_logger = "0.10.0"
futures = "0.3.26"
futures-channel = "0.3.26"
futures-core = "0.3.26"
futures-util = "0.3.26"
hmac = "0.12.1"
http = "0.2.9"
hyper = {version = "0.14.24", features = ["full"]}
log = "0.4.17"
rand = "0.8.5"
reqwest = "0.11.14"
serde = {version = "1.0.152", features = ["derive"]}
sha2 = {version = "0.10.6", features = ["std", "asm", "sha2-asm"]}
tokio = {version = "1.25.0", features = ["full"]}
tokio-stream = "0.1.12"
tonic = "0.9.1"
url = "2.3.1"
zstd = "0.12.3+zstd.1.5.2"
sodiumoxide = "0.2.7"
libsodium-sys = "0.2.7"
hex = "0.4"
byteorder = "1.4.3"
s3s = "0.4.0"
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.16", optional = true, features = ["env-filter", "time"] }
md-5 = "0.10.5"
rusty_ulid = "2.0.0"

[build-dependencies]
tonic-build = "0.9.1"
